// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbjmuvnjhytsdppuxahe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiam11dm5qaHl0c2RwcHV4YWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzIwNzgsImV4cCI6MjA3MzUwODA3OH0.v0akzQQbqepszss0dTcCK0XFAOBgAQuRRJRxpxksWL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});